### ISSUE TITLE
How to extract mutational signature from VCF ?

### ISSUE THREAD

**Issue by a00101** [xqzou/Cell_MutagenSig#1]
Dear developer.

I get used to extract SBS from VCF with 96nucleotide context.
but, I don't know how to extract for 29 indel change used 'compedium mutagenesis 2019 cell' paper.

**Comment by xqzou** [comment]
Hi Seung-Jin,

     If you want the DBS catalogues for all the samples, you can easily
generate it from file Dinucleotides.txt in Figure4_results using one line R
code: data.frame(table(Dinucleotides$Sample, Dinucleotides$dinuc_mutation)).

      The indel catalogues for all the samples were provide by
indel_catalogue.txt in folder Figure5_results.

     Also You can find all the mutation data on Mendeley:
http://doi.org/10.17632/m7r4msjb4c.2. Please let me know if you have
trouble to access the data.

Best wishes,

Xueqing

**Comment by a00101** [comment]
It's a list, not how to extract.
I want classification code or something from vcf file.
for example, 
input : a vcf file
output : 
samples [->1]Mh, [->1]Others, [->1]Rep, [-C]A, [-C]C, [-C]CC, [-C]G, [-C]LongRep, [-C]T, [-T]A
NoName  1  0  1  0  0  0  0  0

And the links says below.

"""
Dataset not found
The dataset you are looking for was not found.

If you think this is a mistake, please let us know.
"""

Thank you for your help. 
But it's insufficient a little bit.

Thanks.

**Comment by xqzou** [comment]
Hi,

      I am also having the same problem. I have contacted Mendeley to check
what's wrong with the link. I will let you know once the link works again.

Best wishes,

Xueqing

**Comment by a00101** [comment]
Thanks.

**Comment by xqzou** [comment]
Hi,

  The link should be working now. Please see the reply below. I did not do
anything to clear my cookies and cache, it just works. So I think it was
probably a temporary issue happened last week. If you still cannot access
it, please let me know.

Best wishes,

Xueqing





Dear Xueqing,

Thank you for contacting Mendeley Support about your dataset that is not
available.

I checked the link you have provided which is
http://doi.org/10.17632/m7r4msjb4c.2 and it is showing fine on my end.

Kindly clear your cookies and cache in your web browser, Kindly click this
link:
https://service.elsevier.com/app/answers/detail/a_id/5117/supporthub/mendeley/kw/cookies/p/16075/
<https://service.elsevier.com/app/answers/detail/a_id/5117/supporthub/mendeley/kw/cookies/p/16075/track/APPiaArTDv8a~RhkGr0a~yCg08sqzC75Mv9b~zj~PP_S>
.

I hope this helps and if you have questions please let me know.


Kind regards,

Michael Angelo David
Research Products Customer Support
Mendeley

**Comment by a00101** [comment]
Thanks. it works well.
